
#ifndef EXTINT_CONFIG_H_
#define EXTINT_CONFIG_H_

/*
 *  LOW_LEVEL
 *  LOGICAL_CHANGE
 *  RISING_EDGE
 *  FALLING_EDGE
 */
#define EXTINT_INT0_TYPE	RISING_EDGE
#define EXTINT_INT1_TYPE	RISING_EDGE
#define EXTINT_INT2_TYPE	RISING_EDGE
/*
 * ENABLE
 * DISABLE
 */
#define EXTINT_INT0_ENABLE	ENABLE
#define EXTINT_INT1_ENABLE	ENABLE
#define EXTINT_INT2_ENABLE	ENABLE



#endif /* EXTINT_CONFIG_H_ */
